name: Example Workflow
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          echo "Running tests..."
          echo "Tests WIP"
          echo "OK"
  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t jon-funk/mimic:latest .